YASM-OBJS-$(CONFIG_POSTPROC) += x86/deinterlace.o
YASM-OBJS-$(CONFIG_POSTPROC) += x86/deblock.o
YASM-OBJS-$(CONFIG_POSTPROC) += x86/transpose.o
YASM-OBJS-$(CONFIG_POSTPROC) += x86/block_copy.o
OBJS += x86/deinterlace.o
